In [12]:
import torch
mask_joint = torch.eye(2)
mask_joint

tensor([[1., 0.],
        [0., 1.]])

In [14]:
mask_marginal = 1 - mask_joint
mask_marginal

tensor([[0., 1.],
        [1., 0.]])

In [8]:
b = torch.tensor([[2, 3], [4, 5]])
c = torch.tensor([[3, 4], [5, 6]])

In [10]:
s = torch.matmul(b, c)
s

tensor([[21, 26],
        [37, 46]])

In [13]:
Ej = (s * mask_joint).mean()
Ej

tensor(16.7500)

In [15]:
Em = torch.exp(s * mask_marginal).mean()
Em

tensor(2.9298e+15)

In [16]:
(Ej - torch.log(Em))

tensor(-18.8637)

In [1]:
import torchvision
from torchvision import transforms as t
from six.moves import urllib
opener = urllib.request.build_opener()
opener.addheaders = [('User-agent', 'Mozilla/5.0')]
urllib.request.install_opener(opener)
train_dataset = torchvision.datasets.MNIST(root='data/mnist/', train=True, download=True, transform=t.ToTensor())
test_dataset = torchvision.datasets.MNIST(root='data/mnist/', train=False, transform=t.ToTensor())

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9912422/9912422 [00:03<00:00, 3211350.29it/s]


Extracting data/mnist/MNIST/raw/train-images-idx3-ubyte.gz to data/mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28881/28881 [00:00<00:00, 105752.42it/s]


Extracting data/mnist/MNIST/raw/train-labels-idx1-ubyte.gz to data/mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1648877/1648877 [00:01<00:00, 999651.27it/s] 


Extracting data/mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to data/mnist/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4542/4542 [00:00<00:00, 3400058.68it/s]

Extracting data/mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/mnist/MNIST/raw

